### PR TITLE
 fix mutex races conditions and run govet on travis

### LINKED ISSUE #121: Crash on destroy
#  Version Reports:

### Distro  version of host:

openSUSE 42.2

### Terraform Version Report

Terraform v0.8.8

### Libvirt version

2.0.0

### terraform-provider-libvirt plugin version (git-hash)

``` git log```
___
# Description of Issue/Question

Got this panic:

```
panic: sync: unlock of unlocked mutex
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: goroutine 45 [running]:
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: panic(0x9f8a40, 0xc420325760)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/runtime/panic.go:500 +0x1a1
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: sync.(*Mutex).Unlock(0xc420437218)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/sync/mutex.go:111 +0x104
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.LibVirtPoolSync.ReleaseLock(0xc42016ef00, 0x0, 0xc4203256f8, 0x8)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/pool_sync.go:48 +0xe2
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.RemoveVolume(0xc420208be0, 0xc4202fcf00, 0x2c, 0x0, 0x0)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/utils.go:101 +0x6ff
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtVolumeDelete(0xc4203170e0, 0x9d9840, 0xc420208be8, 0xc4202539c8, 0x414cd4)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go:352 +0x7b
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420377260, 0xc4202b6aa0, 0xc420313860, 0x9d9840, 0xc420208be8, 0x1, 0xc420426600, 0x18)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:137 +0x3eb
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4203773e0, 0xc4202b6a50, 0xc4202b6aa0, 0xc420313860, 0x0, 0x0, 0x0)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:212 +0x9b
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4203fe040, 0xc4203137e0, 0xc420325720, 0x0, 0x0)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/home/alvaro/Development/go/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: reflect.Value.call(0xc420284480, 0xc4202089e0, 0x13, 0xae7eb4, 0x4, 0xc420253ef0, 0x3, 0x3, 0xc42002eec8, 0x552e69, ...)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/reflect/value.go:434 +0x5c8
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: reflect.Value.Call(0xc420284480, 0xc4202089e0, 0x13, 0xc420253ef0, 0x3, 0x3, 0xc420131338, 0xc42016f740, 0xc42002eeec)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/reflect/value.go:302 +0xa4
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: net/rpc.(*service).call(0xc4203fd980, 0xc4203fd940, 0xc42041a4d8, 0xc42020b780, 0xc42043c200, 0x9db940, 0xc4203137e0, 0x16, 0x9db980, 0xc420325720, ...)
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/net/rpc/server.go:383 +0x148
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: created by net/rpc.(*Server).ServeCodec
2017/04/08 01:19:40 [DEBUG] plugin: terraform-provider-libvirt: 	/usr/lib64/go/src/net/rpc/server.go:477 +0x421
2017/04/08 01:19:40 [DEBUG] plugin: /home/alvaro/Applications/terraform-provider-libvirt: plugin process exited
```

### LINKED ISSUE #240: run "go vet" in travis ci
# Tasks:

- [ ] fix all go vet problem
- [ ] enable go vet on travis.

- depend on #159 ( there are 3 go vet errors due to PoolSync

### PR DESCRIPTION
**Pull request by MalloZup**
fix #240 
 fix #121

### CODE REVIEW

**Comment by MalloZup** [comment]
@inercia you might take a look on 2nd commit :sunflower:

File: libvirt/resource_libvirt_volume.go [hunk 1]
```diff
@@ -90,8 +90,8 @@ func resourceLibvirtVolumeCreate(d *schema.ResourceData, meta interface{}) error
 		poolName = d.Get("pool").(string)
 	}
 
-	PoolSync.AcquireLock(poolName)
-	defer PoolSync.ReleaseLock(poolName)
+	mutexKV.Lock(poolName)
```
Comment (inercia) [inline libvirt/resource_libvirt_volume.go]: A really small comment: instead of `mutexKV`, I would use a name that references the pool, `poolMutexKV` or something like that, so it clearly states that this is about the _pool_...

Comment (MalloZup) [reply libvirt/resource_libvirt_volume.go]: ok thx i will do it :sunflower:

**Comment by MalloZup** [comment]
@inercia  feel free to merge it if you have the superpowers :rofl: I update the change as asked.
Thx :it:
